### ISSUE TITLE
[Feature Req] Move to 6.x (mainline linux has support for h616)

### ISSUE THREAD

**Issue by stisa** [bigtreetech/CB1-Kernel#5]
According to https://linux-sunxi.org/H616#Mainline_Support since kernel 6.0 linux mainline has support for h616, which should make it easier to support it.

**Comment by Haxk20** [comment]
Im the guy who is mainlining CB1. No it is not ready.

**Comment by emersonsc** [comment]
> Im the guy who is mainlining CB1. No it is not ready.

Do you have an ETA on when it will be ready?
Also, what are the issues that make it "not ready"?

**Comment by Haxk20** [comment]
> > Im the guy who is mainlining CB1. No it is not ready.
> 
> Do you have an ETA on when it will be ready?
> Also, what are the issues that make it "not ready"?

No ETA. Cant even guess.

As for the issues. Tons of drivers have to be rewritten to be of a quality thats acceptable. Upstream will not accept the code in this repo as its simply nasty. Most of the code has hacked paths to make it work. 

Whats working right now is Booting into system. UART and USB. Wifi works with out of tree driver that wont get accepted and someone has to make a driver for the chip thats clean and according to datasheet. HDMI works but that code is miles and miles away from being put in upstream.

The rest were not tested. Things are shaping nicely but its really a long waiting game. I would be surprised if we have a fully working board by the end of this year. Thats simply because i and others have other jobs that actually pay the bills. This is a hobby.

**Comment by bigtreetech** [comment]
Please refer [here](https://github.com/bigtreetech/build/tree/CB1-pr). This script can directly build the CB1 Image of the [6.1.29 kernel](https://github.com/bigtreetech/linux/tree/linux-6.1.y-cb1)
